<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2019 Schirrms
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here
	'Class:GenericPhysCommConnector' => 'Connector Type',
	'Class:GenericPhysCommConnector/Attribute:type' => 'Physical connector type',
	'Class:GenericPhysCommConnector/Attribute:type+' => 'This is the form of the connector (RJ-45, Fiber LC...)',
	'Class:GenericPhysCommConnector/Attribute:comment' => 'Comments',
	'Class:GenericPhysCommConnector/Attribute:genericcommphysinterface_list' => 'Interfaces with this connector list',
	'Class:GenericCommProtocol' => 'Connection Protocol',
	'Class:GenericCommProtocol/Attribute:protocol' => 'Connection protocol',
	'Class:GenericCommProtocol/Attribute:protocol+' => 'This is the low level protocol of communication between the devices on this interface (also known as \'Layer Two protocol\' for network connections)',
	'Class:GenericCommProtocol/Attribute:comment' => 'Comments',
	'Class:GenericCommProtocol/Attribute:genericcomminterface_list' => 'Interfaces using this protocol list',
	'Class:GenericCommSpeed' => 'Interface Speed',
	'Class:GenericCommSpeed/Attribute:humanspeed' => 'Human readable interface speed',
	'Class:GenericCommSpeed/Attribute:humanspeed+' => 'This field is read only, and calculated from the speed in bit per second',
	'Class:GenericCommSpeed/Attribute:bitspeed' => 'interface speed in bit per second',
	'Class:GenericCommSpeed/Attribute:comment' => 'Comments',
	'Class:GenericCommSpeed/Attribute:genericcomminterface_list' => 'Interfaces running at this speed',
	'Class:VirtualCommRedundancy' => 'Redundancy Mode',
	'Class:VirtualCommRedundancy/Attribute:redundancy' => 'Functional redundancy name',
	'Class:VirtualCommRedundancy/Attribute:protocol' => 'Redundancy mode',
	'Class:VirtualCommRedundancy/Attribute:protocol+' => 'This is the king of protocol used by the device to ensure redundancy (LACP, Active/tandby...)',
	'Class:VirtualCommRedundancy/Attribute:comment' => 'Comments',
	'Class:VirtualCommRedundancy/Attribute:virtualcommredundancy_list' => 'Virtual interfaces using this redundancy protocol',
	'Class:GenericCommInterface' => 'Connection General Interface',
	'Class:GenericCommInterface/Attribute:name' => 'Name',
	'Class:GenericCommInterface/Attribute:physicaladdress' => 'Physical Layer Address',
	'Class:GenericCommInterface/Attribute:physicaladdress+' => 'Something like a MAC address, a WWN. In Networking, a \'Layer two\' address',
	'Class:GenericCommInterface/Attribute:comment' => 'Comments',
	'Class:GenericCommInterface/Attribute:commproto_id' => 'Connection Protocol',
	'Class:GenericCommInterface/Attribute:commproto_proto' => 'Connection Protocol',
	'Class:GenericCommInterface/Attribute:connectableci_id' => 'Device containing this interface',
	'Class:GenericCommInterface/Attribute:genericcommvirtinterface_list' => 'Virtual interfaces using this interface',
	'Class:GenericCommInterface/Attribute:humanspeed_id' => 'Human readable interface speed',
	'Class:GenericCommInterface/Attribute:humanspeed_speed' => 'Human readable interface speed',
	'Class:GenericCommInterface/Attribute:connectabledevice_id' => 'Local Device Name',
	'Class:GenericCommInterface/Attribute:virtinterfacemember_id' => 'member of Virtual Interface',
	'Class:GenericCommInterface/Attribute:virtinterfacemember_name' => 'member of Virtual Interface',
	'Class:GenericCommPhysInterface' => 'Physical Connection Interface',
	'Class:GenericCommPhysInterface/Attribute:physcommtype_id' => 'Physical connector type',
	'Class:GenericCommPhysInterface/Attribute:physcommtype_type' => 'Physical connector type',
	'Class:GenericCommPhysInterface/Attribute:connected_to_device_id' => 'Connected to remote device',
	'Class:GenericCommPhysInterface/Attribute:connected_to_device_name' => 'Connected to remote device',
	'Class:GenericCommPhysInterface/Attribute:connected_to_id' => 'Interface connected on remote device',
	'Class:GenericCommPhysInterface/Attribute:connected_to_name' => 'Interface connected on remote device',
	'Class:GenericCommPhysInterface/Attribute:connection_impact' => 'Impacts other side or depends on it ?',
	'Class:GenericCommPhysInterface/Attribute:connection_impact+' => 'If the loss of this connection impacts me, I depend on it. If the loss impacts the other side, I impact',
	'Class:GenericCommVirtInterface' => 'Virtual Connection Interface',
	'Class:GenericCommVirtInterface/Attribute:virtualcommredundancy_id' => 'Redundancy kind',
	'Class:GenericCommVirtInterface/Attribute:virtualcommredundancy_id+' => 'Select the Redundancy kind used on this virtual interface, if any',
	'Class:GenericCommVirtInterface/Attribute:virtualcommredundancy_redundancy' => 'Redundancy kind',
	'Class:GenericCommVirtInterface/Attribute:virtualcommredundancy_redundancy+' => 'Select the Redundancy kind used on this virtual interface, if any',
	'Class:GenericCommVirtInterface/Attribute:redundancyType' => 'Redundancy Mode',
	'Class:GenericCommVirtInterface/Attribute:redundancyType+' => 'Select here the level of dependancy for the redundancy',
	'Class:GenericCommVirtInterface/Attribute:genericcomminterface_list' => 'Parent Interfaces list',
	'Class:lnkGenericCommInterfaceToGenericCommVirtInterface' => 'Link Generic Comm Interface to Virtual Comm Interface',
	'Class:lnkGenericCommInterfaceToGenericCommVirtInterface/Attribute:genericcomminterface id' => 'Generic Interface ID',
	'Class:lnkGenericCommInterfaceToGenericCommVirtInterface/Attribute:genericcomminterface id_friendlyname' => 'Generic Interface Name',
	'Class:lnkGenericCommInterfaceToGenericCommVirtInterface/Attribute:genericcommvirtinterface id' => 'Virtual Interface ID',
	'Class:lnkGenericCommInterfaceToGenericCommVirtInterface/Attribute:genericvirtcomminterface id_friendlyname' => 'Virtual Interface Name',
	'Class:GenericCommDeviceType' => 'Generic Connection Device Category',
	'Class:GenericCommDeviceType/Attribute:name' => 'Category Name',
	'Class:GenericCommDeviceType/Attribute:genericcommdevices_list' => 'Devices of this category',
	'Class:GenericCommDevice' => 'Generic Connection Device',
	'Class:GenericCommDevice/Attribute:name' => 'Device Name',
	'Class:GenericCommDevice/Attribute:genericcommdevicetype_id' => 'Device category',
	'Class:GenericCommDevice/Attribute:genericcommdevicetype_name' => 'Device category',
	'Class:GenericCommDevice/Attribute:iosversion_id' => 'OS / Firmware version',
	'Class:GenericCommDevice/Attribute:iosversion_name' => 'OS / Firmware version',
	'Class:ConnectableCI/Attribute:genericcommphysinterface_list' => 'Physical Connection Interface(s)',
	'Class:ConnectableCI/Attribute:genericcommvirtinterface_list' => 'Virtual Connection Interface(s)',
	'Class:ConnectableCI/Attribute:logicalredundancy' => 'Itop Logical Redundancy',
	'Class:ConnectableCI/Attribute:dependantgencommci0_list' => 'List of devices depending from this device, Set 0',
	'Class:ConnectableCI/Attribute:impactorgencommci0_list' => 'List of devices impacting this device, Set 0',
	'Class:ConnectableCI/Attribute:GenCommRedundancy0' => 'Redundancy type for set 0',
	'Class:ConnectableCI/Attribute:dependantgencommci1_list' => 'List of devices depending from this device, Set 1',
	'Class:ConnectableCI/Attribute:impactorgencommci1_list' => 'List of devices impacting this device, Set 1',
	'Class:ConnectableCI/Attribute:GenCommRedundancy1' => 'Redundancy type for set 1',
	'Class:ConnectableCI/Attribute:dependantgencommci2_list' => 'List of devices depending from this device, Set 2',
	'Class:ConnectableCI/Attribute:impactorgencommci2_list' => 'List of devices impacting this device, Set 2',
	'Class:ConnectableCI/Attribute:GenCommRedundancy2' => 'Redundancy type for set 2',
	'Class:ConnectableCI/Attribute:dependantgencommci3_list' => 'List of devices depending from this device, Set 3',
	'Class:ConnectableCI/Attribute:impactorgencommci3_list' => 'List of devices impacting this device, Set 3',
	'Class:ConnectableCI/Attribute:GenCommRedundancy3' => 'Redundancy type for set 3',
	'Class:ConnectableCI/Attribute:dependantgencommci4_list' => 'List of devices depending from this device, Set 4',
	'Class:ConnectableCI/Attribute:impactorgencommci4_list' => 'List of devices impacting this device, Set 4',
	'Class:ConnectableCI/Attribute:GenCommRedundancy4' => 'Redundancy type for set 4',
	'Class:ConnectableCI/Attribute:dependantgencommci5_list' => 'List of devices depending from this device, Set 5',
	'Class:ConnectableCI/Attribute:impactorgencommci5_list' => 'List of devices impacting this device, Set 5',
	'Class:ConnectableCI/Attribute:GenCommRedundancy5' => 'Redundancy type for set 5',
	'Class:ConnectableCI/Attribute:dependantgencommci6_list' => 'List of devices depending from this device, Set 6',
	'Class:ConnectableCI/Attribute:impactorgencommci6_list' => 'List of devices impacting this device, Set 6',
	'Class:ConnectableCI/Attribute:GenCommRedundancy6' => 'Redundancy type for set 6',
	'Class:ConnectableCI/Attribute:dependantgencommci7_list' => 'List of devices depending from this device, Set 7',
	'Class:ConnectableCI/Attribute:impactorgencommci7_list' => 'List of devices impacting this device, Set 7',
	'Class:ConnectableCI/Attribute:GenCommRedundancy7' => 'Redundancy type for set 7',
	'Class:ConnectableCI/Attribute:dependantgencommci8_list' => 'List of devices depending from this device, Set 8',
	'Class:ConnectableCI/Attribute:impactorgencommci8_list' => 'List of devices impacting this device, Set 8',
	'Class:ConnectableCI/Attribute:GenCommRedundancy8' => 'Redundancy type for set 8',
	'Class:ConnectableCI/Attribute:dependantgencommci9_list' => 'List of devices depending from this device, Set 9',
	'Class:ConnectableCI/Attribute:impactorgencommci9_list' => 'List of devices impacting this device, Set 9',
	'Class:ConnectableCI/Attribute:GenCommRedundancy9' => 'Redundancy type for set 9',
));
?>
